services:
  - type: web
    name: risetogether
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 100 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
